{
 "title": "Docker Metrics",
 "description": "Docker Monitoring Template",
 "tags": [
  "docker",
  "prometheus",
  "node-exporter",
  "cadvisor"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cAdvisorName",
    "label": "cAdvisor Target Name",
    "query": "EMT PROD cAdvisor, EMT STAG cAdvisor, KTT PROD cAdvisor, KTT STAG cAdvisor, METRICS PROD cAdvisor, AMT PROD cAdvisor, AMT STAG cAdvisor"
   },
   {
    "name": "nodeExporterName",
    "label": "Node Exporter Target Name",
    "query": "EMT PROD Node Exporter, EMT STAG Node Exporter, KTT PROD Node Exporter, KTT STAG Node Exporter, METRICS PROD Node Exporter, AMT PROD Node Exporter, AMT STAG Node Exporter"
   }
  ]
 },
 "panels": [
  { "title": "Host Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"Prometheus\"}"
    }
   ]
  },
  {
   "title": "Targets Recently Gone Down",
   "type": "graph",
   "description": "Number of Targets Recently Gone Down.\nIf graph goes up to 1 then 1 target has gone down and so on.\nThis graph will always go back down to 0 because its only looking at the difference in target numbers over time.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(targets_up[4m]) - targets_up",
     "legendFormat": "Prometheus Targets Recently Gone Down"
    }
   ]
  },
  {
   "title": "Containers Recently Gone Down",
   "type": "graph",
   "description": "Number of Containers Recently Gone Down.\nIf graph goes up to 1 then 1 container has gone down and so on.\nThis graph will always go back down to 0 because its only looking at the difference in container numbers over time.",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(container_last_seen:count[4m]) - container_last_seen:count",
     "legendFormat": "Number of Containers Recently Gone Down"
    }
   ]
  },
  { "title": "Alert List", "type": "alertlist", "gridPos": { "h": 22, "w": 5, "x": 19, "y": 1 } },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"$nodeExporterName\"}) - sum(node_memory_MemFree_bytes{job=\"$nodeExporterName\"} + node_memory_Buffers_bytes{job=\"$nodeExporterName\"} + node_memory_Cached_bytes{job=\"$nodeExporterName\"}) ) / sum(node_memory_MemTotal_bytes{job=\"$nodeExporterName\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_user_seconds_total{id=\"/docker\", job=\"$cAdvisorName\"}[1m]) * 100) / count(node_cpu_seconds_total{mode=\"system\", job=\"$nodeExporterName\"})"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{job=\"$cAdvisorName\"} - container_fs_usage_bytes{job=\"$cAdvisorName\"}) / sum(container_fs_limit_bytes{job=\"$cAdvisorName\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"EMT PROD Node Exporter\"}) - sum(node_memory_MemFree_bytes{job=\"EMT PROD Node Exporter\"} + node_memory_Buffers_bytes{job=\"EMT PROD Node Exporter\"} + node_memory_Cached_bytes{job=\"EMT PROD Node Exporter\"}) ) / sum(node_memory_MemTotal_bytes{job=\"EMT PROD Node Exporter\"}) * 100",
     "legendFormat": "Memory Usage (EMT PROD)"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"EMT STAG Node Exporter\"}) - sum(node_memory_MemFree_bytes{job=\"EMT STAG Node Exporter\"} + node_memory_Buffers_bytes{job=\"EMT STAG Node Exporter\"} + node_memory_Cached_bytes{job=\"EMT STAG Node Exporter\"}) ) / sum(node_memory_MemTotal_bytes{job=\"EMT STAG Node Exporter\"}) * 100",
     "legendFormat": "Memory Usage (EMT STAG)"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"KTT PROD Node Exporter\"}) - sum(node_memory_MemFree_bytes{job=\"KTT PROD Node Exporter\"} + node_memory_Buffers_bytes{job=\"KTT PROD Node Exporter\"} + node_memory_Cached_bytes{job=\"KTT PROD Node Exporter\"}) ) / sum(node_memory_MemTotal_bytes{job=\"KTT PROD Node Exporter\"}) * 100",
     "legendFormat": "Memory Usage (KTT  PROD)"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"KTT STAG Node Exporter\"}) - sum(node_memory_MemFree_bytes{job=\"KTT STAG Node Exporter\"} + node_memory_Buffers_bytes{job=\"KTT STAG Node Exporter\"} + node_memory_Cached_bytes{job=\"KTT STAG Node Exporter\"}) ) / sum(node_memory_MemTotal_bytes{job=\"KTT STAG Node Exporter\"}) * 100",
     "legendFormat": "Memory Usage (KTT  STAG)"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"METRICS PROD Node Exporter\"}) - sum(node_memory_MemFree_bytes{job=\"METRICS PROD Node Exporter\"} + node_memory_Buffers_bytes{job=\"METRICS PROD Node Exporter\"} + node_memory_Cached_bytes{job=\"METRICS PROD Node Exporter\"}) ) / sum(node_memory_MemTotal_bytes{job=\"METRICS PROD Node Exporter\"}) * 100",
     "legendFormat": "Memory Usage (METRICS PROD)"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"AMT PROD Node Exporter\"}) - sum(node_memory_MemFree_bytes{job=\"AMT PROD Node Exporter\"} + node_memory_Buffers_bytes{job=\"AMT PROD Node Exporter\"} + node_memory_Cached_bytes{job=\"AMT PROD Node Exporter\"}) ) / sum(node_memory_MemTotal_bytes{job=\"AMT PROD Node Exporter\"}) * 100",
     "legendFormat": "Memory Usage (AMT PROD)"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"AMT STAG Node Exporter\"}) - sum(node_memory_MemFree_bytes{job=\"AMT STAG Node Exporter\"} + node_memory_Buffers_bytes{job=\"AMT STAG Node Exporter\"} + node_memory_Cached_bytes{job=\"AMT STAG Node Exporter\"}) ) / sum(node_memory_MemTotal_bytes{job=\"AMT STAG Node Exporter\"}) * 100",
     "legendFormat": "Memory Usage (AMT STAG)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_user_seconds_total{id=\"/docker\", job=\"EMT PROD cAdvisor\"}[1m]) * 100) / count(node_cpu_seconds_total{mode=\"system\", job=\"EMT PROD Node Exporter\"})",
     "legendFormat": "CPU Usage (EMT PROD)"
    },
    {
     "expr": "sum (rate(container_cpu_user_seconds_total{id=\"/docker\", job=\"EMT STAG cAdvisor\"}[1m]) * 100) / count(node_cpu_seconds_total{mode=\"system\", job=\"EMT STAG Node Exporter\"})",
     "legendFormat": "CPU Usage (EMT STAG)"
    },
    {
     "expr": "sum (rate(container_cpu_user_seconds_total{id=\"/docker\", job=\"KTT PROD cAdvisor\"}[1m]) * 100) / count(node_cpu_seconds_total{mode=\"system\", job=\"KTT PROD Node Exporter\"})",
     "legendFormat": "CPU Usage (KTT PROD)"
    },
    {
     "expr": "sum (rate(container_cpu_user_seconds_total{id=\"/docker\", job=\"KTT STAG cAdvisor\"}[1m]) * 100) / count(node_cpu_seconds_total{mode=\"system\", job=\"KTT STAG Node Exporter\"})",
     "legendFormat": "CPU Usage (KTT STAG)"
    },
    {
     "expr": "sum (rate(container_cpu_user_seconds_total{id=\"/docker\", job=\"METRICS PROD cAdvisor\"}[1m]) * 100) / count(node_cpu_seconds_total{mode=\"system\", job=\"METRICS PROD Node Exporter\"})",
     "legendFormat": "CPU Usage (METRICS PROD)"
    },
    {
     "expr": "sum (rate(container_cpu_user_seconds_total{id=\"/docker\", job=\"AMT PROD cAdvisor\"}[1m]) * 100) / count(node_cpu_seconds_total{mode=\"system\", job=\"AMT PROD Node Exporter\"})",
     "legendFormat": "CPU Usage (AMT PROD)"
    },
    {
     "expr": "sum (rate(container_cpu_user_seconds_total{id=\"/docker\", job=\"AMT STAG cAdvisor\"}[1m]) * 100) / count(node_cpu_seconds_total{mode=\"system\", job=\"AMT STAG Node Exporter\"})",
     "legendFormat": "CPU Usage (AMT STAG)"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes {job=\"EMT PROD Node Exporter\", instance=~\"atvts2493.athtem.eei.ericsson.se.*\", device=~\"/dev/.*\", mountpoint=\"/etc/hosts\"} / 1000000",
     "legendFormat": "Free Storage ({{job }})"
    },
    {
     "expr": "node_filesystem_free_bytes {job=\"EMT STAG Node Exporter\", instance=~\"atvts3360.athtem.eei.ericsson.se.*\", device=~\"/dev/.*\", mountpoint=\"/etc/hosts\"} / 1000000",
     "legendFormat": "Free Storage ({{job }})"
    },
    {
     "expr": "node_filesystem_free_bytes {job=\"KTT PROD Node Exporter\", instance=~\"atvts2496.athtem.eei.ericsson.se.*\", device=~\"/dev/.*\", mountpoint=\"/etc/hosts\"} / 1000000",
     "legendFormat": "Free Storage ({{job }})"
    },
    {
     "expr": "node_filesystem_free_bytes {job=\"KTT STAG Node Exporter\", instance=~\"atvts2754.athtem.eei.ericsson.se.*\", device=~\"/dev/.*\", mountpoint=\"/etc/hosts\"} / 1000000",
     "legendFormat": "Free Storage ({{job }})"
    },
    {
     "expr": "node_filesystem_free_bytes {job=\"METRICS PROD Node Exporter\", instance=~\"nodeExporter.*\", device=~\"/dev/.*\", mountpoint=\"/etc/hosts\"} / 1000000",
     "legendFormat": "Free Storage ({{job }})"
    },
    {
     "expr": "node_filesystem_free_bytes {job=\"Node Exporter\", instance=~\"nginx:80.*\", device=~\"/dev/.*\", mountpoint=\"/etc/hosts\"} / 1000000",
     "legendFormat": "Free Storage (Local {{job }})"
    },
    {
     "expr": "node_filesystem_free_bytes {job=\"AMT PROD Node Exporter\", instance=~\"atvts2497.athtem.eei.ericsson.se.*\", device=~\"/dev/.*\", mountpoint=\"/etc/hosts\"} / 1000000",
     "legendFormat": "Free Storage ({{job }})"
    },
    {
     "expr": "node_filesystem_free_bytes {job=\"AMT STAG Node Exporter\", instance=~\"atvts2753.athtem.eei.ericsson.se.*\", device=~\"/dev/.*\", mountpoint=\"/etc/hosts\"} / 1000000",
     "legendFormat": "Free Storage ({{job }})"
    }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\", job=\"$cAdvisorName\"}[$interval])) by (id)",
     "legendFormat": "RECEIVE"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\", job=\"$cAdvisorName\"}[$interval])) by (id)",
     "legendFormat": "TRANSMIT"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"$nodeExporterName\"}) - sum(node_memory_MemAvailable_bytes{job=\"$nodeExporterName\"})",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(node_memory_MemAvailable_bytes{job=\"$nodeExporterName\"})",
     "legendFormat": "Available Memory"
    }
   ]
  },
  { "title": "Container Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "description": "Average Container CPU usage in the last 10 seconds",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{image!=\"\", job=\"$cAdvisorName\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\", job=\"$cAdvisorName\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\", job=\"$cAdvisorName\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\", job=\"$cAdvisorName\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}