{
 "title": "KTT Express Metrics",
 "tags": [
  "Express",
  "KTT"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "expressName",
    "label": "Express Target Name",
    "query": "KTT PROD Express, KTT STAG Express"
   }
  ]
 },
 "panels": [
  { "title": "Express Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Active Handles",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=\"$expressName\"}"
    }
   ]
  },
  {
   "title": "Total Active Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "nodejs_active_requests_total{job=\"$expressName\"}"
    }
   ]
  },
  {
   "title": "Heap Size Used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(rate(nodejs_heap_size_used_bytes{job=\"$expressName\"}[1m]) / nodejs_heap_size_total_bytes{job=\"$expressName\"}) * 100"
    }
   ]
  },
  {
   "title": "Express Eventloop Lag (Seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=\"$expressName\"} * 1000",
     "legendFormat": "Milliseconds"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (method) (increase(responses{job=\"$expressName\"}[10y]))"
    }
   ]
  },
  {
   "title": "Number of Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(numOfRequests{job=\"$expressName\"}[10y])"
    }
   ]
  },
  {
   "title": "Number of Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (job, status) (increase(responses{job=\"$expressName\"}[10y]))"
    }
   ]
  }
 ]
}