{
 "title": "MongoDB Metrics",
 "description": "MongoDB Prometheus Exporter Dashboard",
 "tags": [ "MongoDB" ],
 "time": { "from": "now/M", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "vAppName",
    "label": "vApp Name",
    "query": "atvts2493.athtem.eei.ericsson.se, atvts3360.athtem.eei.ericsson.se, atvts2340.athtem.eei.ericsson.se, atvts2754.athtem.eei.ericsson.se, atvts2462.athtem.eei.ericsson.se, atvts2753.athtem.eei.ericsson.se"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$vAppName.*\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_metrics_document_total{instance=~\"$vAppName.*\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_metrics_query_executor_total{instance=~\"$vAppName.*\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Health metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "env" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{instance=~\"$vAppName.*\"}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_connections{instance=~\"$vAppName.*\",state=\"available\"}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_connections{instance=~\"$vAppName.*\",state=\"current\"}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{instance=~\"$vAppName.*\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{instance=~\"$vAppName.*\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Disk Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Disk Reads Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$vAppName.*\"}[$interval])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Writes Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$vAppName.*\"}[$interval])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  }
 ]
}